kind: List
apiVersion: v1
metadata: {}

items:
  - apiVersion: v1
    kind: Template
    template: oshinko-rest
    metadata:
      name: oshinko-rest
      annotations:
        description: Launch the Oshinko Apache Spark cluster management Rest API server.
        openshift.io/display-name: Oshinko Rest endpoints
    objects:
      - kind: Service
        apiVersion: v1
        metadata:
          name: ${OSHINKO_REST_NAME}-proxy
          labels:
            name: ${OSHINKO_REST_NAME}-proxy
        spec:
          ports:
          - name: oc-proxy-port
            protocol: TCP
            port: 8001
            targetPort: 8001
          selector:
            name: ${OSHINKO_REST_NAME}
      - kind: Service
        apiVersion: v1
        metadata:
          name: ${OSHINKO_REST_NAME}
          labels:
            name: ${OSHINKO_REST_NAME}
        spec:
          ports:
            - name: o-web-port
              protocol: TCP
              port: 8080
              targetPort: 8080
          selector:
            name: ${OSHINKO_REST_NAME}
      - kind: Route
        apiVersion: v1
        metadata:
          name: ${OSHINKO_REST_NAME}
        spec:
          host: ${OSHINKO_REST_ROUTE_HOSTNAME}
          path: /
          to:
            kind: Service
            name: ${OSHINKO_REST_NAME}
          alternateBackends:
            - kind: Service
              name: ${OSHINKO_REST_NAME}
      - kind: DeploymentConfig
        apiVersion: v1
        metadata:
          name: ${OSHINKO_REST_NAME}
        spec:
          strategy:
            type: Rolling
          triggers:
            - type: ConfigChange
          replicas: 1
          selector:
            name: ${OSHINKO_REST_NAME}
          template:
            metadata:
              labels:
                name: ${OSHINKO_REST_NAME}
            spec:
              containers:
                - name: ${OSHINKO_REST_NAME}
                  image: ${OSHINKO_REST_IMAGE}
                  imagePullPolicy: Always
                  ports:
                    - name: o-web-port
                      containerPort: 8080
                      protocol: TCP
                  env:
                    - name: OSHINKO_CLUSTER_NAMESPACE
                      valeu: ${OSHINKO_CLUSTER_NAMESPACE}
                    - name: SPARK_DEFAULT
                      value: ${SPARK_DEFAULT}
                    - name: OSHINKO_REFRESH_INTERVAL
                      value: ${OSHINKO_REFRESH_INTERVAL}
                    - name: WEB_ROUTE_NAME
                      value: ${OSHINKO_REST_NAME}
                    - name: INSECURE_WEBUI
                      value: "true"
                    - name: CURRENT_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                - name: oc-proxy
                  image: ${OSHINKO_WEB_IMAGE}
                  imagePullPolicy: IfNotPresent
                  command:
                    - "/usr/src/app/oc"
                  args:
                    - proxy
                    - "-p"
                    - '8001'
                    - "--address=0.0.0.0"
                    - "--disable-filter=true"
                    - "--api-prefix=/proxy"
                  ports:
                    - name: oc-proxy-port
                      containerPort: 8001
                      protocol: TCP
              serviceAccount: oshinko
    parameters:
      - name: OSHINKO_CLUSTER_NAMESPACE
        description: The target namespace in which Oshinko clusters will be managed
        required: false
        value: "oshinko"
      - name: SPARK_DEFAULT
        description: Full name of the spark image to use when creating clusters
        required: false
      - name: OSHINKO_REST_NAME
        description: Name of the oshinko web service
        value: "oshinko-rest"
      - name: OSHINKO_REST_IMAGE
        description: Full name of the oshinko web image
        required: true
        value: radanalyticsio/oshinko-rest:stable
      - name: OSHINKO_WEB_IMAGE
        description: Full name of the oshinko web image
        required: true
        value: radanalyticsio/oshinko-webui:stable
      - name: OSHINKO_REST_ROUTE_HOSTNAME
        description: The hostname used to create the external route for the webui
      - name: OSHINKO_REFRESH_INTERVAL
        value: "5"
        description: Refresh interval for updating cluster list in seconds
